name: APK
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 18
        uses: actions/setup-java@v4.0.0

        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.0.0

  package:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 18
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Touch local properties
        run: touch local.properties

      - name: Update API_KEY
        run:
          touch secrets.properties
          echo API_KEY=${{ secrets.API_KEY }} >> secrets.properties
          cat secrets.properties

      - name: Update BASE_URL KEY
        run:
          touch secrets.properties
          echo BASE_URL=${{ secrets.API_KEY }} >> secrets.properties
          cat secrets.properties

      - name: Create Google Services JSON File
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'google-services.json'
          fileDir: './app'
          encodedString: ${{ secrets.GOOGLE_SERVICE_JSON }}

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: meow-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
