name: Ktlint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0

        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.0.0

#      - name: Update API KEY
#        run:
#          echo 'API_KEY=${{ secrets.API_KEY }}' >> ./secrets.properties
#
#      - name: Update BASE_URL KEY
#        run:
#          echo 'BASE_URL=${{ secrets.BASE_URL }}' >> ./secrets.properties

  format-ktlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 18
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Create-Test-properties
        run:
          echo API_KEY="https://api.thecatapi.com/v2/" > secrets.properties
          echo BASE_URL="https://api.thecatapi.com/v3/" >> secrets.properties

      - uses: actions/upload-artifact@v4
        with:
          name: secrets.properties





