name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 18
        uses: actions/setup-java@v4.0.0

        with:
          distribution: 'temurin'
          java-version: '18'
          cache: gradle

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.0.0

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1

      - name: Set up JDK 18
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: gradle

      - name: Touch local properties
        run: touch local.properties

      - name: Create Google Services JSON File
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'google-services.json'
          fileDir: './app'
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Test
        run: ./gradlew test
